from .doctor_main import DoctorMain
from .add_prescription import AddPrescription
from .add_medicine_to_prescription import AddMedicineToPrescription
from .doctor_past_prescriptions import DoctorPastPrescriptions
from .doctor_view_prescription_details import DoctorViewPrescriptionDetails
from .doctor_list_medicies import DoctorListMedicines